-- ============================================================
-- PostgreSQL V2: account_records / character_records（登录/选角/存档）
-- ============================================================
CREATE TABLE IF NOT EXISTS account_records (
    id SERIAL PRIMARY KEY,
    name VARCHAR(13) NOT NULL DEFAULT '',
    password VARCHAR(128) NOT NULL DEFAULT '',
    temporary_password_hash VARCHAR(60) NOT NULL DEFAULT '',
    temporary_password_expires_at VARCHAR(64) NOT NULL DEFAULT '',
    pin VARCHAR(10) NOT NULL DEFAULT '',
    pic VARCHAR(26) NOT NULL DEFAULT '',
    logged_in SMALLINT NOT NULL DEFAULT 0,
    last_login TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    birthday DATE NOT NULL DEFAULT '2005-05-11',
    banned SMALLINT NOT NULL DEFAULT 0,
    ban_reason TEXT,
    mac_addresses TEXT,
    nx_credit INTEGER,
    maple_point INTEGER,
    nx_prepaid INTEGER,
    character_slots SMALLINT NOT NULL DEFAULT 3,
    gender SMALLINT NOT NULL DEFAULT 10,
    temp_ban TIMESTAMP NOT NULL DEFAULT '2005-05-11 00:00:00',
    tos SMALLINT NOT NULL DEFAULT 0,
    site_logged TEXT,
    web_admin INTEGER DEFAULT 0,
    nick VARCHAR(20),
    mute INTEGER DEFAULT 0,
    email VARCHAR(45),
    ip TEXT,
    reward_points INTEGER NOT NULL DEFAULT 0,
    vote_points INTEGER NOT NULL DEFAULT 0,
    hwid VARCHAR(12) NOT NULL DEFAULT '',
    language INTEGER NOT NULL DEFAULT 3
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_account_records_name ON account_records(name);
CREATE INDEX IF NOT EXISTS idx_account_records_id_banned ON account_records(id, banned);

CREATE TABLE IF NOT EXISTS character_records (
    id SERIAL PRIMARY KEY,
    account_id INTEGER NOT NULL DEFAULT 0,
    world INTEGER NOT NULL DEFAULT 0,
    name VARCHAR(13) NOT NULL DEFAULT '',
    level INTEGER NOT NULL DEFAULT 1,
    exp INTEGER NOT NULL DEFAULT 0,
    gacha_exp INTEGER NOT NULL DEFAULT 0,
    str_stat INTEGER NOT NULL DEFAULT 12,
    dex_stat INTEGER NOT NULL DEFAULT 5,
    luk_stat INTEGER NOT NULL DEFAULT 4,
    int_stat INTEGER NOT NULL DEFAULT 4,
    hp INTEGER NOT NULL DEFAULT 50,
    mp INTEGER NOT NULL DEFAULT 5,
    max_hp INTEGER NOT NULL DEFAULT 50,
    max_mp INTEGER NOT NULL DEFAULT 5,
    meso INTEGER NOT NULL DEFAULT 0,
    hp_mp_used INTEGER NOT NULL DEFAULT 0,
    job INTEGER NOT NULL DEFAULT 0,
    skin_color INTEGER NOT NULL DEFAULT 0,
    gender INTEGER NOT NULL DEFAULT 0,
    fame INTEGER NOT NULL DEFAULT 0,
    f_quest INTEGER NOT NULL DEFAULT 0,
    hair INTEGER NOT NULL DEFAULT 0,
    face INTEGER NOT NULL DEFAULT 0,
    ap INTEGER NOT NULL DEFAULT 0,
    sp VARCHAR(128) NOT NULL DEFAULT '0,0,0,0,0,0,0,0,0,0',
    map INTEGER NOT NULL DEFAULT 0,
    spawn_point INTEGER NOT NULL DEFAULT 0,
    gm SMALLINT NOT NULL DEFAULT 0,
    party INTEGER NOT NULL DEFAULT 0,
    buddy_capacity INTEGER NOT NULL DEFAULT 25,
    create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    rank INTEGER NOT NULL DEFAULT 1,
    rank_move INTEGER NOT NULL DEFAULT 0,
    job_rank INTEGER NOT NULL DEFAULT 1,
    job_rank_move INTEGER NOT NULL DEFAULT 0,
    guild_id INTEGER NOT NULL DEFAULT 0,
    guild_rank INTEGER NOT NULL DEFAULT 5,
    messenger_id INTEGER NOT NULL DEFAULT 0,
    messenger_position INTEGER NOT NULL DEFAULT 4,
    mount_level INTEGER NOT NULL DEFAULT 1,
    mount_exp INTEGER NOT NULL DEFAULT 0,
    mount_tiredness INTEGER NOT NULL DEFAULT 0,
    omok_wins INTEGER NOT NULL DEFAULT 0,
    omok_losses INTEGER NOT NULL DEFAULT 0,
    omok_ties INTEGER NOT NULL DEFAULT 0,
    match_card_wins INTEGER NOT NULL DEFAULT 0,
    match_card_losses INTEGER NOT NULL DEFAULT 0,
    match_card_ties INTEGER NOT NULL DEFAULT 0,
    merchant_mesos INTEGER DEFAULT 0,
    has_merchant SMALLINT DEFAULT 0,
    equip_slots INTEGER NOT NULL DEFAULT 24,
    use_slots INTEGER NOT NULL DEFAULT 24,
    setup_slots INTEGER NOT NULL DEFAULT 24,
    etc_slots INTEGER NOT NULL DEFAULT 24,
    family_id INTEGER NOT NULL DEFAULT -1,
    monster_book_cover INTEGER NOT NULL DEFAULT 0,
    alliance_rank INTEGER NOT NULL DEFAULT 5,
    vanquisher_stage INTEGER NOT NULL DEFAULT 0,
    ariant_points INTEGER NOT NULL DEFAULT 0,
    dojo_points INTEGER NOT NULL DEFAULT 0,
    last_dojo_stage INTEGER NOT NULL DEFAULT 0,
    finished_dojo_tutorial SMALLINT NOT NULL DEFAULT 0,
    vanquisher_kills INTEGER NOT NULL DEFAULT 0,
    summon_value INTEGER NOT NULL DEFAULT 0,
    partner_id INTEGER NOT NULL DEFAULT 0,
    marriage_item_id INTEGER NOT NULL DEFAULT 0,
    reborns INTEGER NOT NULL DEFAULT 0,
    pq_points INTEGER NOT NULL DEFAULT 0,
    data_string VARCHAR(64) NOT NULL DEFAULT '',
    last_logout_time TIMESTAMP NOT NULL DEFAULT '2015-01-01 05:00:00',
    last_exp_gain_time TIMESTAMP NOT NULL DEFAULT '2015-01-01 05:00:00',
    party_search SMALLINT NOT NULL DEFAULT 1,
    jail_expire BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_character_records_account_id ON character_records(account_id);
CREATE INDEX IF NOT EXISTS idx_character_records_world ON character_records(world);
CREATE INDEX IF NOT EXISTS idx_character_records_ranking_level ON character_records(level, exp);
